module.exports = {
    ACTIVE_DIALOG: "ActiveDialog",
    CULTURE_QUEST: "CultureQuest",
    ETHNO_MAP: "EthnoMap",
    GENERIC: "Generic",
    INFO: "Info",
    INTERACTIVE_TIMELINE: "InteractiveTimeline",
    INTRODUCTION_PAGE: "IntroductionPage",
    LISTENING_COMPREHENSION: "ListeningComprehension",
    MAP: "Map",
    MATCH_ITEM: "MatchItem",
    MULTI_COLUMN_PRONUNCIATION: "MultiColumnPronunciation",
    MULTI_NOTE: "MultiNote",
    MULTIPLE_CHOICE: "MultipleChoice",
    ORDERING: "Ordering",
    PRONUNCIATION: "Pronunciation",
    QUIZ_END: "QuizEnd",
    QUIZ_START: "QuizStart",
    RESPONSE_FORMATION: "ResponseFormation",
    SECTION_END: "SectionEnd",
    SORTING: "Sorting",
    UTTERANCE_FORMATION: "UtteranceFormation",
    VIDEO: "Video"
};