var keyMirror = require('keymirror');

module.exports = keyMirror({
    SETTINGS_CREATE: null,
    SETTINGS_DESTROY: null,
    SETTINGS_TOGGLE_IDS: null,
    SETTINGS_UPDATE_VOICE_VOLUME: null,
    SETTINGS_UPDATE_BACKGROUND_VOLUME: null,
    SETTINGS_UPDATE_AUTO_PLAY_SOUND: null,
    SETTINGS_UPDATE_MUTED: null,
    SETTINGS_VOICE_VOLUME_STEP_UP: null,
    SETTINGS_VOICE_VOLUME_STEP_DOWN: null,
    SETTINGS_BACKGROUND_VOLUME_STEP_UP: null,
    SETTINGS_BACKGROUND_VOLUME_STEP_DOWN: null
});