var tempJSON = {
  "lastModifiedTime" : 1465251632000,
  "pageType" : "PuzzleMap",
  "puzzleMapId" : 20,
  "puzzleName" : "VCAT AFPAK",
  "dialogX" : null,
  "dialogY" : null,
  "lastModifiedBy" : "lcorkett",
  "puzzleMapPieces" : [ {
    "name" : "Afpak Puzzle Map Test 04",
    "imageFileName" : "AFPAK_Puzzle_Map_Test_04.jpg",
    "puzzleMapPieceId" : 215,
    "imageId" : 976,
    "order" : 0,
    "labeledImageId" : null,
    "labeledImageName" : null,
    "correctImageId" : null,
    "correctImageName" : null,
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : null
  }, {
    "name" : "Afghanistan Correct 01",
    "imageFileName" : "Afghanistan_Correct_01.png",
    "puzzleMapPieceId" : 216,
    "imageId" : 977,
    "order" : 1,
    "labeledImageId" : 978,
    "labeledImageName" : "Afghanistan_Labeled_01.png",
    "correctImageId" : 979,
    "correctImageName" : "Afghanistan_Incorrect_01.png",
    "offsetX" : 450,
    "offsetY" : 300,
    "scaleAmount" : null
  }, {
    "name" : "Iran Correct 01",
    "imageFileName" : "Iran_Correct_01.png",
    "puzzleMapPieceId" : 217,
    "imageId" : 980,
    "order" : 2,
    "labeledImageId" : 981,
    "labeledImageName" : "Iran_Labeled_01.png",
    "correctImageId" : 982,
    "correctImageName" : "Iran_Incorrect_01.png",
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : null
  }, {
    "name" : "Pakistan Correct 01",
    "imageFileName" : "Pakistan_Correct_01.png",
    "puzzleMapPieceId" : 218,
    "imageId" : 983,
    "order" : 3,
    "labeledImageId" : 985,
    "labeledImageName" : "Pakistan_Labeled_01.png",
    "correctImageId" : 984,
    "correctImageName" : "Pakistan_Incorrect_01.png",
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : null
  }, {
    "name" : "Tajikistan Correct 01",
    "imageFileName" : "Tajikistan_Correct_01.png",
    "puzzleMapPieceId" : 219,
    "imageId" : 986,
    "order" : 4,
    "labeledImageId" : 988,
    "labeledImageName" : "Tajikistan_Labeled_01.png",
    "correctImageId" : 987,
    "correctImageName" : "Tajikistan_Incorrect_01.png",
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : null
  }, {
    "name" : "Turkmenistan Correct 01",
    "imageFileName" : "Turkmenistan_Correct_01.png",
    "puzzleMapPieceId" : 220,
    "imageId" : 989,
    "order" : 5,
    "labeledImageId" : 991,
    "labeledImageName" : "Turkmenistan_Labeled_01.png",
    "correctImageId" : 990,
    "correctImageName" : "Turkmenistan_Incorrect_01.png",
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : 25
  }, {
    "name" : "Uzbekistan Correct 01",
    "imageFileName" : "Uzbekistan_Correct_01.png",
    "puzzleMapPieceId" : 221,
    "imageId" : 992,
    "order" : 6,
    "labeledImageId" : 994,
    "labeledImageName" : "Uzbekistan_Labeled_01.png",
    "correctImageId" : 993,
    "correctImageName" : "Uzbekistan_Incorrect_01.png",
    "offsetX" : null,
    "offsetY" : null,
    "scaleAmount" : null
  } ]
}